### ISSUE TITLE
Device not found: JSON ERROR => 4: Syntax error

### ISSUE THREAD

**Issue by nzhillnet** [TasmoAdmin/TasmoAdmin#250]
Hi,

Got this errror on one device. Another was discovered sucessfully.

Version 1.6.0 of TasmoAdmin, downloaded today.

```
JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Status":{"Module":1,"FriendlyName":["s1_heaterbelt"],"Topic":"s1_heaterbelt","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"8T02:38:59","StartupUTC":"2018-10-19T22:26:40","Sleep":0,"BootCount":20,"SaveCount":485,"SaveAddress":"F7000"},"StatusFWR":{"Version":"6.1.1","BuildDateTime":"2018-07-21T06:56:57","Boot":6,"Core":"2_4_0","SDK":"2.1.0(deb1901)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":2,"LogHost":"192.168.0.10","LogPort":5140,"SSId":["hillnet_ap",""],"TelePeriod":30,"SetOption":["00008009","55818000"]},"StatusMEM":{"ProgramSize":537,"Free":464,"Heap":9,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FCAE794","00000000","23B6179E","00000000"]},"StatusNET":{"Hostname":"s1_heaterbelt","IPAddress":"192.168.0.200","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.4","Mac":"5C:CF:7F:BC:6F:87","Webserver":2,"WifiConfig":2},"StatusMQT":{"MqttHost":"192.168.0.10","MqttPort":1883,"MqttClientMask":"s1_heaterbelt","MqttClient":"s1_heaterbelt","MqttUser":"hillduino","MqttTsSNS":{"Time":"2018-10-28T02:05:39"},"StatusSTS":{"Time":"2018-10-28T02:05:39","Uptime":"8T02:38:59","Vcc":3.532,"POWER":"0","Wifi":{"AP":1,"SSId":"hillnet_ap","RSSI":96,"APMac":"78:8A:20:57:04:78"}}}
```

--
Thanks,

Roland

**Comment by reloxx13** [comment]
looks like your mqtt username has a bad char, try to re-set in in the GUI of the device and be sure to clean everything in it.

this is mostly happening by invisible control characters. could also be your password or some other value in the mqtt tab.

you can see it at ,"MqttUser":"hillduino","MqttTsSNS"

MqttTsSNS is completly mispelled and the bock before does not getting closed.

you can also check it by calling it in your browser with

http://IPOFYOURDEVICE/cm?cmnd=status%200

maybe you can see the error better there and fix it.

**Comment by HillNet** [comment]
Thanks @reloxx13.

The device I am trying to add has been sucessfully communicating to my mqtt server for quite a while now so I'm not sure if it's a device setup/invisible control characters issue. It's also working as part of an automation setup in Home Assistant.

That said I re-entered the mqtt configutation data using the Tasmota web interface (and saved then rebooted), but it still produces the same error as before when trying to add to TasmoAdmin.

I called 

> http://IPOFYOURDEVICE/cm?cmnd=status%200

And got the following:

`"Status":{"Module":1,"FriendlyName":["s1_heaterbelt"],"Topic":"s1_heaterbelt","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:00:05","StartupUTC":"","Sleep":0,"BootCount":34,"SaveCount":511,"SaveAddress":"F5000"},"StatusFWR":{"Version":"6.1.1","BuildDateTime":"2018-07-21T06:56:57","Boot":6,"Core":"2_4_0","SDK":"2.1.0(deb1901)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":2,"LogHost":"192.168.0.10","LogPort":5140,"SSId":["hillnet_ap",""],"TelePeriod":30,"SetOption":["00008009","55818000"]},"StatusMEM":{"ProgramSize":537,"Free":464,"Heap":13,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FCAE794","00000000","23B6179E","00000000"]},"StatusNET":{"Hostname":"s1_heaterbelt","IPAddress":"192.168.0.200","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.4","Mac":"5C:CF:7F:BC:6F:87","Webserver":2,"WifiConfig":2},"StatusMQT":{"MqttHost":"192.168.0.10","MqttPort":1883,"MqttClientMask":"s1_heaterbelt","MqttClient":"s1_heaterbelt","MqttUser":"hillduino","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15},"StatusTIM":{"UTC":"Thu Jan 01 00:00:05 1970","Local":"Thu Jan 01 00:00:05 1970","StartDST":"Thu Jan 01 00:00:00 1970","EndDST":"Thu Jan 01 00:00:00 1970","Timezone":1,"Sunrise":"07:43","Sunset":"16:03"},"StatusSNS":{"Time":"1970-01-01T00:00:05"},"StatusSTS":{"Time":"1970-01-01T00:00:05","Uptime":"0T00:00:05","Vcc":3.534,"POWER":"0","Wifi":{"AP":1,"SSId":"hillnet_ap","RSSI":100,"APMac":"78:8A:20:57:04:78"}}}
`

I'll reflash the device in 2 weeks once it's finished it's current "job" and see if I can add it then.

Thanks,

--
Roland

**Comment by reloxx13** [comment]
this json looks diffrent and better , thanks for the json, i can work and test with it to reproduce.

**Comment by reloxx13** [comment]
if you did not miss anything, in this response a "{" right at the beginning is missing.

"Status" should be {"Status"
i have tested this response and if i add the { i could success "fake"-add your device.

there is sth wrong with it.

but i also saw that u use core 2.4.0 which is known to be unstable/buggy.
i would suggest you:
if you want to use a newer core version, try the new 2.5.0 on stage (check platformio.ini) OR go back to 2.3.0 for stable.

**Comment by HillNet** [comment]
Hi @reloxx13,

Yes, copy/paste error. You are correct regarding status: `{"Status":{"Module":1,` etc...

Will 2.4.2 be buggy too? I have been using 2.4 on all my boards with no perceived issues. That said I havn't taken anytime to understand what the core code does and the differences of the versions!

I may attempt 2.5.0 on a spare device; will have to see if Tasmota compiles correctly.

Thanks again,

--
Roland

**Comment by xHirscHx** [comment]
same prob have had this issue   for a while device works but its shows red for switch and blackout only in tasmotaadmin.

Could not reach device. Please try again. This happens if the device is restarting or there were too many requests.
JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Status":{"Module":0,"DeviceName":"X_BRCurtains","FriendlyName":["X-brcrelay1","X-brcrelay2","X-brcrelay3","X-brcrelay4"],"Topic":"tas_bedroom_curtains","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1,"InfoRetain":0,"StateRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/release/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:02:15","StartupUTC":"2021-04-16T02:55:19","Sleep":0,"CfgHolder":4617,"BootCount":83,"BCResetTime":"2020-08-27T04:27:50","SaveCount":2627,"SaveAddress":"FA000"},"StatusFWR":{"Version":"9.3.1(tasmota)","BuildDateTime":"2021-03-09T16:12:28","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"442/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Link",""],"TelePeriod":300,"Resolution":"55C180C0","SetOption":["0002C029","2805C8000100060000005A0A000000000000","40000280","00006000","00000000"]},"StatusMEM":{"ProgramSize":593,"Free":408,"Heap":24,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"164020","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"},"StatusNET":{"Hostname":"Tas_curtains","IPAddress":"192.168.1.29","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"8C:AA:B5:1B:33:C5","Webserver":2,"WifiConfig":5,"WifiPower":17.0},"StatusMQT":{"MqttHost":"192.168.1.191","MqttPort":1883,"MqttClientMask":"tas_bedroom_curtains","MqttClient":"tas_bedroom_curtains","MqttUser":"name_here","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30},"StatusTIM":{"UTC":"2021-04-16T02:57:34","Local":"2021-04-16T03:57:34","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"05:56","Sunset":"19:42"},"StatusSNS":{"Time":"2021-04-16T03:57:34","Shutter1":{"Position":0,"Direction":0,"Target":0},"Shutter2":{"Position":0,"Direction":0,"Target":0}},"StatusSTS":{"Time":"2021-04-16T03:57:34","Uptime":"0T00:02:15","UptimeSec":135,"Heap":24,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":636,"MqttCount":1,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"wifi","BSSId":"5E:BA:BA:6E:E3:58","Channel":1,"RSSI":58,"Signal":-71,"LinkCount":1,"Downtime":"0T00:00:04"}},"StatusSHT":{"SHT0":{"Relay1":1,"Relay2":2,"Open":45,"Close":45,"50perc":50,"Delay":20,"Opt":"0000","Calib":[300,500,700,900,1000],"Mode":"0"}},{"SHT1":{"Relay1":3,"Relay2":4,"Open":80,"Close":80,"50perc":50,"Delay":0,"Opt":"0000","Calib":[300,500,700,900,1000],"Mode":"0"}}}}

Reload Page
