### ISSUE TITLE
Can TasmoAdmin be used to push a downgrade?

### ISSUE THREAD

**Issue by mattlward** [TasmoAdmin/TasmoAdmin#271]
I just upgraded my Sonoff devices to 6.4.1 and now one of them is not maintaining a connection to my MQTT broker.  It is a Sonoff POW.  I would like to downgrade the unit to restore stability.  The unit is not restarting, but is just not doing MQTT correctly.  I have rebooted the unit and have power cycled the unit.  I was previously on 6.4.0 and would like to go back to that version.

From the `logs...`
`09:35:16 MQT: Attempting connection...
09:35:17 MQT: Connected
09:35:17 MQT: tele/sonoff-basement/LWT = Online (retained)`

This is happening all the time now and Home Assistant and Hassio show the device and unavailable often, but then it pops back in. 
Thanks Matt

**Comment by mattlward** [comment]
I was able to finally use the utility to push a downgrade to 6.4.0 and all fo the problems have gone away.  Both affected units are now rock solid with mqtt connections to HA.

**Comment by ascillato** [comment]
Hi, TasmoAdmin supports upload any version, but if you go down too far, your config will be scrambled due to Tasmota does not support going backwards in versions. The memory map of the eeprom changes from version to version but it corrects it automatically when upgrading. For downgrading that is not the case.

Anyway, for your case, you can use the latest Tasmota version compiled with core 2.3.0. In some routers core 2.4.2 has issues. As in another routers core 2.3.0 has issues. So it is a matter of testing which arduino core is best for you.

Link to the latest release (6.4.1) with core 2.3.0:
http://thehackbox.org/tasmota/release/020300/

Link to the latest version from development branch (6.4.1.9) with latest core 2.5.0:
http://thehackbox.org/tasmota/020500/
