### ISSUE TITLE
counted saves very high

### ISSUE THREAD

**Issue by kevinwells22** [TasmoAdmin/TasmoAdmin#282]
Hi, in the TasmoAdmin we have 'counted saves', I have a few devices and some are very high, one is at 865, I know for a fact, I have not done that many saves, is there something wrong, not sure whats going on with this value.

**Comment by gknauf** [comment]
I dont think that TasmoAdmin does anything on its own that increases 'counted saves'.
I believe this depends on the configuration and usage of you device; f.e. take a look at the PowerOnState:
https://github.com/arendst/Sonoff-Tasmota/wiki/PowerOnState-Configuration
that sounds to me as if with PowerOnState 3 (default) every switch state of the device gets saved in order to restore it after a power loss; if I switch a device I can see that shortly after the 'counted saves' increases.
You should probably ask about these details at the Tasmota Git:
https://github.com/arendst/Sonoff-Tasmota
