### ISSUE TITLE
Is there a config backup option?

### ISSUE THREAD

**Issue by iptvcld** [TasmoAdmin/TasmoAdmin#354]
Is there a config backup option?

**Comment by oldjohngalt** [comment]
Would it be possible to integrate with https://github.com/tasmota/decode-config to backup the device configurations?

**Comment by buzurk26** [comment]
+1

**Comment by daballiemo** [comment]
+1

**Comment by reloxx13** [comment]
not as easy as you think.

maybe sth easier as save the dumped file and send it back to restore (without reading any option in it).

**Comment by inverse** [comment]
Could be possible by plugging in `decode-config` but that would bloat the image somewhat as that is Python specific

**Comment by DSDV** [comment]
maybe integrate https://github.com/danmed/TasmoBackupV1

a single interface for everything tasmota would be huge!

**Comment by starsoccer** [comment]
+1 would be great if there was just a way to run a backup config command on each device and then either get each file individually or get a zip with all the configs.

**Comment by inverse** [comment]
Add basic support in https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.3.0-beta1

Adds new backup page which provides the ability to select 1 or more.

Need to improve the error handling but it'd a start

**Comment by inverse** [comment]
https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.3.0-beta2 has some better error handling :+1:

**Comment by starsoccer** [comment]
Can confirm it works for me, 2 notes though:

1. It seems to backup by ID rather then human readable name which makes it hard to know which is for which device. It would be great if it could backup using the human readable name, or maybe make it a checkbox to configure which way it backs up
2. While everything backed up, I am not sure if the backups are actually good/valid or not. I thought the easiest way to check would be to do checksum of the file and of a new backup, but doing this gave different values. Im not sure if this is just because some small amount of data changes each time in the backup like the date/time or something. The backup isnt really human readable so I didnt have a way to manually check and confirm it looks good or not and would prefer to avoid testing it on a device.

**Comment by inverse** [comment]
1. The name field isn't unique - I could concat them though. e.g. `<id>-<name>.dmp`

2. You could leverage https://github.com/tasmota/decode-config to convert the `dmp` file into something more human readable and then do a diff of the two. The backup itself is just invoking the `dl` command on the device and zipping it up.

**Comment by inverse** [comment]
https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.3.0-beta3 - includes the name naming schema

**Comment by starsoccer** [comment]
> 1. The name field isn't unique - I could concat them though. e.g. `<id>-<name>.dmp`
> 
>     2. You could leverage https://github.com/tasmota/decode-config to convert the `dmp` file into something more human readable and then do a diff of the two. The backup itself is just invoking the `dl` command on the device and zipping it up.

Awesome thanks, I checked and most of the differences were due to timestamps and boot count. The only thing I noticed that was different decoded was `save_flag`. Doing it manually it seems to be set to 125, but using your tool its 47

> https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.3.0-beta3 - includes the name naming schema

Awesome, confirmed it works. Any idea if there is an API for tasmoadmin? Id love to be able to schedule backups to a NAS/SMB share. on a daily basis or something like that.

**Comment by inverse** [comment]
> Awesome thanks, I checked and most of the differences were due to timestamps and boot count. The only thing I noticed that was different decoded was save_flag. Doing it manually it seems to be set to 125, but using your tool its 47

Interesting - Not sure what that flag is for - do you now?

> Awesome, confirmed it works. Any idea if there is an API for tasmoadmin? Id love to be able to schedule backups to a NAS/SMB share. on a daily basis or something like that.

No API yet - Please open another issue with your requirements - Improved the output for failures since it might miss some devices. That could be turned into an API though like indicating what devices failed to backup.

**Comment by starsoccer** [comment]
I do not know what the flag is for.

Issue made here, https://github.com/TasmoAdmin/TasmoAdmin/issues/750
