### ISSUE TITLE
autoscan not working when password involved ?

### ISSUE THREAD

**Issue by carefulcomputer** [TasmoAdmin/TasmoAdmin#412]
I have a strange problem. When I do autoscan , (enter IP range and password ), it can't find any device. however when I add a device one at a time using direct IP address it is able to find and add the device. What could I be doing wrong ?

**Comment by qwertangel** [comment]
For all other folks who have same issue, one clunky workaround is to edit tasmoadmin/devices.csv and add the ip's in bulk manually, one per line.. like this..

<sr.number>,	<name>,	<ip>,<username>,<password>,bulb_1,<sr.number>

e.g.
1, bedroom_switch, 192.168.1.2, myusername, mysecret, bulb_1,	1
2, livingroom_switch, 192.168.1.3, myusername, mysecret, bulb_1,2

that way you wouldn't have to add one device at a time in UI. 
You can even put full range of ip's which you are not sure if they have tasmota or not (e.g. 192.168.1.1 to 192.168.1.254). When tasmoamdin sees this file, it will read status of each device. For devices which are active it will show online status and you can remove the ones which show offline (because there is no tasmota on those devices) by editing file again.

**Comment by inverse** [comment]
That's strange - is it still an issue for you? I've not seen this one before.
