### ISSUE TITLE
Updating procedure seems not working

### ISSUE THREAD

**Issue by edegraaff** [TasmoAdmin/TasmoAdmin#437]
Hi, 
Great tool to manage the tasmota devices ! 
I am facing one problem regarding the updating proces, it does not work at my environment.
I have the tasmoadmin as docker on my synology as a bridge 
the devices are found, the version is showed but updating is problematic, i tried all kind of options and it fails

Devices are shown by :http://192.168.1.xx:49154/devices please notice portnr due the docker bridge 

configrured as alternative this tasmota update url
http://ota.tasmota.com and port 80 
in the start it was 192.168.1.xx: port 49154 

i cant get the automatic update working, and would be happy to have this in place

regards

eelco

**Comment by GoNzCiD** [comment]
I already have the same issue.

I have also the docker environment. It was working fine in last versions, but I can't upgrade any device since the 9.3.1tasmota version (this was the last that tasmoadmin upgrade automatically)

I have tried to change the URL and I have checked that the .bin file is downloable.

The update log says that the firmware was uploaded, but the device is not uploaded neither rebooted.

But the tasmota log says:
```
.../light/floor/UPGRADE = {"Upgrade":"Failed Wrong HTTP Code"}
```

And I see this issue https://github.com/reloxx13/TasmoAdmin/issues/310

I'm using the v1.7.0 tasmoadmin.

**Comment by edegraaff** [comment]
i fixed it by making some changes in the configuration. otaserver ip of tje docker server, ota server port portnr of remapped port 80 by docker see port settings, firmware version i changed it to tasmoa-nl  ota use ssl off

**Comment by GoNzCiD** [comment]
Thanks @edegraaff, it also works for me!

**Comment by boxi360** [comment]
I do following:
Step 1:

![image](https://user-images.githubusercontent.com/60380162/145958076-fea23fd1-baba-47e5-bf1e-e3cc0f7c87b7.png)

Step 2:

![image](https://user-images.githubusercontent.com/60380162/145958237-2ea5e277-deb6-4b9b-9a47-972f17f47360.png)

Upgrade is done

**Comment by Ajimaru** [comment]
This is maybe releated to this issue [https://github.com/reloxx13/TasmoAdmin/issues/448#issuecomment-969127205](url)

**Comment by edegraaff** [comment]
Where you able to do the upgrade to version 10 of tasmoa? I failed that one needed to do it on manual.

**Comment by boxi360** [comment]
> Where you able to do the upgrade to version 10 of tasmoa? I failed that one needed to do it on manual.

Unfortunately, it no longer works automatically.
You simply have to execute two commands and then it updates itself to the current version.

1. Select all devices
2. put "OtaUrl http://ota.tasmota.com/tasmota/release/tasmota.bin"
3. put upgrade 1
4. wait for finish

**Comment by inverse** [comment]
Is this still an issue?

**Comment by GoNzCiD** [comment]
Yes @inverse, the issue is still present. But the workaround of using the command console works.

**Comment by inverse** [comment]
@GoNzCiD We def need to improve that update flow was thinking of outputting the URLs for the firmware on  the  upload form so that you can easily test what URLs will be provided to the devices.

Plus additionally checking on the JS side before serving it to the devices, sounds something around that.

**Comment by alexdelprete** [comment]
> We def need to improve that update flow

I'm on 2.0b7, and updates don't work anymore in AUTO mode. Up to a couple of versions ago AUTO updates were working fine, now the tasmota-minimal.bin is flashed, but the tasmota.bin is not. I was wondering if TA always flashes minimal first and the full binary after or there's some checking logic first.

Also, TasmoAdmin is pulling binaries from the release branch (http://ota.tasmota.com/tasmota/release/), it would be nice if we could also choose the dev branch (most current one, url: http://ota.tasmota.com/tasmota/) in the settings.

I've solved the problem temporarily using the Command feature, sending the following command (actually it's a concatenation of two commands through the Backlog command) to ALL devices:

`Backlog OtaUrl http://ota.tasmota.com/tasmota/tasmota.bin; Upgrade 1;`

Last thing: when selecting gzip option, the files downloaded in data folder are always .bin. Is that a bug or it's simply a renamed gzip file?

**Comment by inverse** [comment]
> I'm on 2.0b7, and updates don't work anymore in AUTO mode. Up to a couple of versions ago AUTO updates were working fine, now the tasmota-minimal.bin is flashed, but the tasmota.bin is not. I was wondering if TA always flashes minimal first and the full binary after or there's some checking logic first.

Interesting - I didn't change anything around the flashing logic (that whole JS is a bit of a mess) I only reworked the backend code into more moduler and testable code.

> Also, TasmoAdmin is pulling binaries from the release branch (http://ota.tasmota.com/tasmota/release/), it would be nice if we could also choose the dev branch (most current one, url: http://ota.tasmota.com/tasmota/) in the settings.

Please add another issue for this so it can be handled. Currently we're pulling releases from GitHub from this endpoint https://api.github.com/repos/arendst/Tasmota/releases/latest 

> Last thing: when selecting gzip option, the files downloaded in data folder are always .bin. Is that a bug or it's simply a renamed gzip file?

Good catch https://github.com/TasmoAdmin/TasmoAdmin/pull/567 should fix it - config always saves as string due to `trim()`

I published a new beta release with additional fixes in.

**Comment by inverse** [comment]
@alexdelprete published https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.0.0-beta8 which should fix your first point and the gzip one :)

**Comment by alexdelprete** [comment]
Malachi, that was quick. So, I need to test #567 and #568 and report back. Thank you so much.

BTW: I now remember our first encounter: it was for the emoncms addon. :)

**Comment by inverse** [comment]
No worries - I did a lot of refactoring in this 2.0.0 release (some bugs along the way - but there are tests in a lot of places now)

Unfortunately the Home Assistant addon adopted the beta branch so that's pushed me to fix stuff a bit quicker :see_no_evil: 

Oh yeah! I remember - I need to get back to improving that at some point but time is short outside of work.

**Comment by alexdelprete** [comment]
> Home Assistant addon adopted the beta branch so that's pushed me to fix stuff a bit quicker

Good for us users! :)

> I need to get back to improving that at some point but time is short outside of work.

I'm not using it anymore, the energy integration in HA is enough. But if you need any help on testing it let me know and I'll install it again. :)

**Comment by alexdelprete** [comment]
> Please add another issue for this so it can be handled.

Done. #573

**Comment by alexdelprete** [comment]
Fixes #567 and #568 have been tested, they worked perfectly.

I actually downgraded one of the Sonoff TX3 from 12.0.2.1 to 12.0.2 because of #573. :)

![image](https://user-images.githubusercontent.com/7027842/174683192-5b197b75-2f7d-4d85-a092-1982d9c87e5b.png)

![image](https://user-images.githubusercontent.com/7027842/174683206-bf79ef27-5031-4307-a5f5-48d4c33ef3f5.png)

![image](https://user-images.githubusercontent.com/7027842/174683224-a0590fdc-4279-4337-a3ff-4b1ba3f89f9d.png)

**Comment by broyuken** [comment]
This still seems to be an issue, but the workaround with the two commands above seem to have worked nicely.

**Comment by edegraaff** [comment]
for me all is working in prem on an old pi2
