### ISSUE TITLE
Removal of minimal firmware handling

### ISSUE THREAD

**Issue by inverse** [TasmoAdmin/TasmoAdmin#633]
When redoing `device_update.js` in the 2.1.0 releases I noticed that the handling for minimal firmwares as never called. See: https://github.com/TasmoAdmin/TasmoAdmin/blob/ea332c5edbf16e59b621bf3361ad8f51fb398b7e/tasmoadmin/resources/js/device_update.js#L21

Should this be removed completely since it serves no purpose currently? Or should it handled correctly? If so what was the intended flow for that? 

cc @alexdelprete @reloxx13

**Comment by alexdelprete** [comment]
The upgrade flow is described [here](https://tasmota.github.io/docs/Upgrading/). Basically, if you want to be ABSOLUTELY SURE there are no issues upgrading to a different build, and don't use gz firmware binaries, you first install the minimal version then upgrade to the full one.

![image](https://user-images.githubusercontent.com/7027842/186512359-dfa7806c-9ad0-4d3e-b32b-1accfbc1e1ba.png)

![image](https://user-images.githubusercontent.com/7027842/186512317-ab3f7d7c-68cc-4368-915c-190f2bae8cfa.png)

But, since the introduction of gz binaries, this double step is not needed anymore.

![image](https://user-images.githubusercontent.com/7027842/186513156-d8a9ef0f-20ef-418d-8a3b-0bd51cde5eb3.png)

So what I would suggest is: if the user selects the gz binaries, you can skip downloading the minimal and executing the double step upgrade process.

If the user doesn't select it, the double-step upgrade is still the safest upgrade flow.

**Comment by inverse** [comment]
:pray: thanks for such a detailed answer :)

Whats interesting is the code I linked before I refactored things was commented out wiring up the initial minimal firmware setup. I checked when that was done and it was 4 years ago :/

However I remember seeing my devices flash with that minimal header during the update process... but not sure how :/

**Comment by alexdelprete** [comment]
> thanks for such a detailed answer :)

my pleasure, I try to help devs to the extent possible.

> However I remember seeing my devices flash with that minimal header during the update process... but not sure how

Yes I remember the first time I tried the auto upgrade, it didn't work and it got stuck, on the device the minimal version was flashed.

**Comment by inverse** [comment]
Right now there is a toggle for gzip or not in the settings - I think this should be dropped.

And then be similarly implemented as you described.

auto OTA uses gz releases since a long time so not an issue (it'll always fetch latest)

If uploaded manual firmware gz then skip minimal requirement, if it's not gz then require minimal.

**Comment by alexdelprete** [comment]
> If uploaded manual firmware gz then skip minimal requirement, if it's not gz then require minimal.

The only doubt I have is when tasmota devs write "will likely skip". :)

I would do it this way: if the device fw is > 8.2 then .gz and skip minimal step. If it's below...probably it's a very old device...so we have to be careful. :)

**Comment by inverse** [comment]
Auto will always download the latest version so we're beyond the need for minimal

Also with the manual upload the code would need to know the version of the firmware being uploaded... to perform such checks... Wonder how we could infer that from the binary?

> The only doubt I have is when tasmota devs write "will likely skip". :)

What do you mean by that?

**Comment by alexdelprete** [comment]
> What do you mean by that?

From what devs wrote here:

![image](https://user-images.githubusercontent.com/7027842/197443445-7e14b956-72d1-4628-9bda-f45277ddcab3.png)

**Comment by inverse** [comment]
So minimal is required since even with gz binaries the firmware will look for a matching `tasmota-minimal.bin.gz` binary at the OTA server.

**Comment by alexdelprete** [comment]
and why did it work in the other branch? you had the minimal there?

so, in the end, my concerns were valid...minimal is still there with us. :)

**Comment by inverse** [comment]
Yeah master was downloading the firmware :/ Yup! we use the minimal one even if you don't explicitly point the OTA endpoint to it first :)

It looks for the a file at the OTA server at the same level and tried to resolve it - if its not there it fails the upgrade.

**Comment by alexdelprete** [comment]
> It looks for the a file at the OTA server at the same level and tried to resolve it - if its not there it fails the upgrade.

so we just need to download the necessary files. good.
