### ISSUE TITLE
Documentation update needed due error message 

### ISSUE THREAD

**Issue by edegraaff** [TasmoAdmin/TasmoAdmin#794]
i updated to the lasest version today. ## PUBLISHED ### v2.1.0
Extracted the tasmoadmin files and set the owner to www-data restarted apache and i expected a working version but i get an error
I haven't updated my pi for quite a while so i did first an update and upgrade and php is now version 7.4 running bullseye 

## Expected Behavior
after extracting the files  (stopped apache first) and installed the last version i expected a login prompt or the tasmoa device list as usual.

## Current Behavior

Warning: require_once(/var/www/tasmoadmin/tasmoadmin/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/tasmoadmin/tasmoadmin/includes/bootstrap.php on line 58

Fatal error: require_once(): Failed opening required '/var/www/tasmoadmin/tasmoadmin/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/tasmoadmin/tasmoadmin/includes/bootstrap.php on line 58

## Possible Solution
Maybe i missed some steps. I followed the documentation https://github.com/TasmoAdmin/TasmoAdmin/wiki/Guide-for-Ubuntu-Server-16.04 but it is a bit outdated. 

## Steps to Reproduce
1. reinstalled with no success
2. reinstalled the backup versin
3. after replace the olf version it worked again v1.8.0 - [TasmoAdmin GitHub ](https://github.com/reloxx13/TasmoAdmin)- [Tasmota GitHub](https://github.com/arendst/Tasmota)
4.

## Context (Environment)
LAMP ENVIRONMENT 
## Context (Device)
reason to update was due fail of the last update of my devices to tasmoa 12.4.0 > stopped and fallback to manual update

## Detailed Description
i hope this is complete enough

## Possible Implementation
update documentation 
i will recheck based on the documentation and or suggestions

thanks
regards
eelco

**Comment by edegraaff** [comment]
Documentation issue stays, i make an error in using the wrong distrubution. i pulled the code :-(
This one works :-) https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.4.2
Suggestion to save configuration before overwrite the whole /var/www/tasmoadmin folder

thanks for your software! 

regards
eelco

**Comment by inverse** [comment]
Yeah the guides on the wiki are quite out of date and are more community maintained - we recommend the docker based install for easier compatibility/support. 

What zip did you download? 

![image](https://user-images.githubusercontent.com/713525/220198619-ef1402f0-ae33-41eb-aa65-b19c2a5580d2.png)

This one should still work as it includes the required vendor library (otherwise you'll need to use composer to install)

Version 3.0.0 will be coming out soon and will require PHP 8.1 as PHP 7.4 is end of life since last year.

**Comment by edegraaff** [comment]
Great, jes i made an error, on my pi2 i can;'t run dockers, but the main version with lamp will still work. ..  , please keep in mind your project is great, and running it on an old pi or pi zero is great for once and a while update all the tamoas..

**Comment by inverse** [comment]
It should work with what you've got if you just download the zip release I highlighted - otherwise you'll need additional dependencies for the build process.

As for version 3.0.0 that will be coming out next - as long as you can upgrade to PHP 8.1 you'll be fine - it shouldn't be that much of a change .
