### ISSUE TITLE
Update 3.x. installed - PHP Error

### ISSUE THREAD

**Issue by mymeyer** [TasmoAdmin/TasmoAdmin#824]
Hello , have installed the latest update and now get this error. What can I do about it ?

"Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.33. in /var/www/html/tasmoadmin/vendor/composer/platform_check.php on line 24".

System runs under Proxmox.
Linux Tasmota 5.15.85-1-pve #1 SMP PVE 5.15.85-1 (2023-02-01T00:00Z) x86_64 GNU/Linux

Reg.
Michael

**Comment by mafrei2019** [comment]
steht doch da.
UPDATE zuerst von PHP auf 8.x

**Comment by mymeyer** [comment]
> 

Habe ich so nicht verstanden, aber werde es gerne testen. Merci..

**Comment by mafrei2019** [comment]
Es funktioniert mit PHP 8.2

**Comment by PrinzEisenherz1** [comment]
Ich habe das selbe Problem. Leider ist die Anleitung schon sehr alt (ubuntu 16.04).
Kannst Du mir kurz erklären wie Du das update gemacht hast?
TasmoAdmin läuft bei mir in einem LXC-Container (Debian Bullseye) mit php7.4.
Wäre echt klasse wenn jemand mir den Udateprozess erklären könnte.

Gruß
Johnny

**Comment by inverse** [comment]
Yeah the minimum PHP version was bumped to PHP 8.1 due to PHP 7.4 being end of life. We bumped the major version of the addon as there was another change which will help us evolve the application by moving routing internally so nginx/apache configuration changes will be required. It's documented in https://github.com/TasmoAdmin/TasmoAdmin/blob/master/UPGRADE.md#from-2---3


As for updating your setup to support newer versions. Using the pre-build docker images would be the easiest way to go but that's not always possible.

It's been a while since I've done it but I remember  Ondřej Surý PPA being good for Debian based distos. 

E.g. https://www.linuxshelltips.com/install-php-8-debian/

**Comment by inverse** [comment]
@mymeyer are you unblocked or need more guidance?

**Comment by mymeyer** [comment]
Done.
